import { describe, expect, it, vi } from 'vitest';

import { ApiError, EdgeBlockedError, UnauthorizedError, createApiClient, detectEdgeBlock } from './index.js';

/**
 * The CloudFront page Zola's mobile API answered with on 2026-10-01
 * (chrischall/mcp-host#1015): a 403 in 35 ms that never reached the origin.
 */
const CLOUDFRONT_BLOCK = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 7xXbE3cOQ2V0nY_example==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>`;

const CLOUDFLARE_BLOCK = `<!DOCTYPE html><html><head><title>Attention Required! | Cloudflare</title></head>
<body><div id="cf-error-details"><h1>Sorry, you have been blocked</h1></div></body></html>`;

const CLOUDFLARE_CHALLENGE = `<!DOCTYPE html><html><head><title>Just a moment...</title></head>
<body><script>window._cf_chl_opt={cvId:'3'}</script></body></html>`;

const AKAMAI_BLOCK = `<HTML><HEAD><TITLE>Access Denied</TITLE></HEAD><BODY>
<H1>Access Denied</H1>You don't have permission to access "http://api.example.com/v1/me" on this server.<P>
Reference&#32;&#35;18&#46;5d1c2e17&#46;1727800000&#46;abc123
<P>https&#58;&#47;&#47;errors&#46;edgesuite&#46;net&#47;18&#46;5d1c2e17
</BODY></HTML>`;

const IMPERVA_BLOCK = `<html><head><META NAME="robots" CONTENT="noindex,nofollow"></head>
<body>Request unsuccessful. Incapsula incident ID: 1234000560012345678-90123456789</body></html>`;

describe('detectEdgeBlock', () => {
  it('recognises the CloudFront "request could not be satisfied" page', () => {
    expect(detectEdgeBlock({ body: CLOUDFRONT_BLOCK })).toEqual({ vendor: 'CloudFront' });
  });

  it('recognises a Cloudflare block page and a Cloudflare challenge', () => {
    expect(detectEdgeBlock({ body: CLOUDFLARE_BLOCK })).toEqual({ vendor: 'Cloudflare' });
    expect(detectEdgeBlock({ body: CLOUDFLARE_CHALLENGE })).toEqual({ vendor: 'Cloudflare' });
  });

  it('recognises a Cloudflare mitigation from the cf-mitigated header alone', () => {
    const headers = new Headers({ 'cf-mitigated': 'challenge' });
    expect(detectEdgeBlock({ body: '', headers })).toEqual({ vendor: 'Cloudflare' });
    expect(detectEdgeBlock({ headers: { 'CF-Mitigated': 'challenge' } })).toEqual({ vendor: 'Cloudflare' });
  });

  it('recognises Akamai and Imperva block pages', () => {
    expect(detectEdgeBlock({ body: AKAMAI_BLOCK })).toEqual({ vendor: 'Akamai' });
    expect(detectEdgeBlock({ body: IMPERVA_BLOCK })).toEqual({ vendor: 'Imperva' });
  });

  it('does not call an origin auth error a block, even when it passed through CloudFront', () => {
    // CloudFront stamps `x-cache: Error from cloudfront` on EVERY error it
    // relays, the origin's own 401/403 included — so that header is not
    // evidence of a block, and treating it as one would hide a real rejection.
    const headers = new Headers({ 'x-cache': 'Error from cloudfront', via: '1.1 abc.cloudfront.net (CloudFront)' });
    expect(detectEdgeBlock({ body: '{"error":"invalid_token"}', headers })).toBeNull();
  });

  it('does not call a CDN outage page a block: the same markers on a 5xx mean the origin is down', () => {
    // CloudFront shows "The request could not be satisfied" on its 502/504
    // pages too, and Cloudflare's cf-error-details on its 52x pages. Those say
    // the API is unreachable, not that this host is blocked.
    expect(detectEdgeBlock({ body: CLOUDFRONT_BLOCK, status: 502 })).toBeNull();
    expect(detectEdgeBlock({ body: CLOUDFRONT_BLOCK, status: 504 })).toBeNull();
    expect(detectEdgeBlock({ body: CLOUDFLARE_BLOCK, status: 522 })).toBeNull();
    expect(detectEdgeBlock({ body: CLOUDFRONT_BLOCK, status: 403 })).toEqual({ vendor: 'CloudFront' });
  });

  it('calls a challenge or a cf-mitigated response a block at any status', () => {
    expect(detectEdgeBlock({ body: CLOUDFLARE_CHALLENGE, status: 503 })).toEqual({ vendor: 'Cloudflare' });
    expect(detectEdgeBlock({ status: 503, headers: { 'cf-mitigated': 'challenge' } })).toEqual({ vendor: 'Cloudflare' });
  });

  it('does not call a sign-in page or an ordinary HTML error a block', () => {
    expect(detectEdgeBlock({ body: '<html><title>Sign in</title><form action="/login"></form></html>' })).toBeNull();
    expect(detectEdgeBlock({ body: '<html><title>403 Forbidden</title><h1>Forbidden</h1></html>' })).toBeNull();
    expect(detectEdgeBlock({ body: 'Access Denied' })).toBeNull();
    expect(detectEdgeBlock({})).toBeNull();
  });
});

function stubFetch(res: Response) {
  return vi.fn(async () => res) as unknown as typeof fetch;
}

describe('createApiClient on a CDN block', () => {
  it('throws EdgeBlockedError (an ApiError carrying the status) for a CloudFront block page', async () => {
    const client = createApiClient({
      baseUrl: 'https://mobile-api.zola.test',
      getToken: () => 't',
      serviceName: 'Zola',
      fetchImpl: stubFetch(new Response(CLOUDFRONT_BLOCK, { status: 403, headers: { 'content-type': 'text/html' } })),
    });
    const err = await client.fetchJson('GET', '/v4/your-wedding').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect(err).toBeInstanceOf(ApiError);
    expect((err as EdgeBlockedError).status).toBe(403);
    expect((err as EdgeBlockedError).vendor).toBe('CloudFront');
    expect((err as Error).message).toMatch(/blocked at its CDN\/WAF \(CloudFront\)/);
    expect((err as Error).message).toMatch(/credential was not evaluated/);
    // The page itself is noise in a tool error; the message names what it was.
    expect((err as Error).message).not.toContain('<HTML>');
  });

  it('throws EdgeBlockedError from fetchHtml and fetchRaw too', async () => {
    for (const method of ['fetchHtml', 'fetchRaw'] as const) {
      const client = createApiClient({
        baseUrl: 'https://x.test',
        getToken: () => 't',
        fetchImpl: stubFetch(new Response(CLOUDFLARE_BLOCK, { status: 403 })),
      });
      const err = await client[method]('GET', '/a').catch((e: unknown) => e);
      expect(err, method).toBeInstanceOf(EdgeBlockedError);
      expect((err as EdgeBlockedError).vendor, method).toBe('Cloudflare');
    }
  });

  it('honours a cf-mitigated header on a bodyless refusal', async () => {
    const client = createApiClient({
      baseUrl: 'https://x.test',
      getToken: () => 't',
      fetchImpl: stubFetch(new Response('', { status: 403, headers: { 'cf-mitigated': 'challenge' } })),
    });
    const err = await client.fetchJson('GET', '/a').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
  });

  it('keeps a CloudFront 502 a plain ApiError: the origin is down, nothing was blocked', async () => {
    const client = createApiClient({
      baseUrl: 'https://x.test',
      getToken: () => 't',
      fetchImpl: stubFetch(new Response(CLOUDFRONT_BLOCK.replace('403 ERROR', '502 ERROR'), { status: 502 })),
      retry: { count: 0, delayMs: 0 },
    });
    const err = await client.fetchJson('GET', '/a').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ApiError);
    expect(err).not.toBeInstanceOf(EdgeBlockedError);
  });

  it('keeps an origin 403 a plain ApiError', async () => {
    const client = createApiClient({
      baseUrl: 'https://x.test',
      getToken: () => 't',
      fetchImpl: stubFetch(
        new Response('{"error":"forbidden"}', { status: 403, headers: { 'x-cache': 'Error from cloudfront' } }),
      ),
    });
    const err = await client.fetchJson('GET', '/a').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ApiError);
    expect(err).not.toBeInstanceOf(EdgeBlockedError);
  });
});

describe('createApiClient on a CDN block served with a 401', () => {
  // CloudFront, Akamai and Imperva sometimes refuse with a 401 rather than a
  // 403. Mapping that straight to UnauthorizedError — "the token is bad" —
  // sends somebody to re-sign in with a credential nothing ever looked at.
  const html = { 'content-type': 'text/html' };

  it('throws EdgeBlockedError for a CloudFront refusal page on a 401, from every fetch method', async () => {
    for (const method of ['fetchJson', 'fetchHtml', 'fetchRaw'] as const) {
      const client = createApiClient({
        baseUrl: 'https://x.test',
        getToken: () => 'tok-secret',
        serviceName: 'Svc',
        fetchImpl: stubFetch(new Response(CLOUDFRONT_BLOCK.replace('403 ERROR', '401 ERROR'), { status: 401, headers: html })),
      });
      const err = await client[method]('GET', '/me').catch((e: unknown) => e);
      expect(err, method).toBeInstanceOf(EdgeBlockedError);
      expect(err, method).not.toBeInstanceOf(UnauthorizedError);
      expect((err as EdgeBlockedError).status, method).toBe(401);
      expect((err as EdgeBlockedError).vendor, method).toBe('CloudFront');
      expect((err as Error).message, method).not.toContain('tok-secret');
      expect((err as Error).message, method).not.toContain('<HTML>');
    }
  });

  it('throws EdgeBlockedError for an Akamai or Imperva page on a 401', async () => {
    for (const [page, vendor] of [
      [AKAMAI_BLOCK, 'Akamai'],
      [IMPERVA_BLOCK, 'Imperva'],
    ] as const) {
      const client = createApiClient({
        baseUrl: 'https://x.test',
        getToken: () => 't',
        fetchImpl: stubFetch(new Response(page, { status: 401, headers: html })),
      });
      const err = await client.fetchJson('GET', '/me').catch((e: unknown) => e);
      expect(err, vendor).toBeInstanceOf(EdgeBlockedError);
      expect((err as EdgeBlockedError).vendor, vendor).toBe(vendor);
    }
  });

  it('honours a cf-mitigated header on a 401, whatever the body', async () => {
    const client = createApiClient({
      baseUrl: 'https://x.test',
      getToken: () => 't',
      fetchImpl: stubFetch(
        new Response('{"error":"x"}', {
          status: 401,
          headers: { 'cf-mitigated': 'challenge', 'content-type': 'application/json' },
        }),
      ),
    });
    const err = await client.fetchJson('GET', '/me').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect((err as EdgeBlockedError).vendor).toBe('Cloudflare');
  });

  it('bypasses onUnauthorized for a block: nothing judged the credential, so nothing should re-sign in', async () => {
    const onUnauthorized = vi.fn(() => new Error('re-login'));
    const client = createApiClient({
      baseUrl: 'https://x.test',
      getToken: () => 't',
      onUnauthorized,
      fetchImpl: stubFetch(new Response(IMPERVA_BLOCK, { status: 401, headers: html })),
    });
    await expect(client.fetchJson('GET', '/me')).rejects.toBeInstanceOf(EdgeBlockedError);
    expect(onUnauthorized).not.toHaveBeenCalled();
  });

  it('keeps an ordinary 401 an UnauthorizedError — JSON, plain text or an origin HTML page', async () => {
    const bodies: Array<[string, Record<string, string>]> = [
      ['{"error":"invalid_token"}', { 'content-type': 'application/json', 'x-cache': 'Error from cloudfront' }],
      ['bad token tok-secret', { 'content-type': 'text/plain' }],
      ['<html><title>401 Unauthorized</title><body>Sign in</body></html>', html],
    ];
    for (const [body, headers] of bodies) {
      const client = createApiClient({
        baseUrl: 'https://x.test',
        getToken: () => 'tok-secret',
        fetchImpl: stubFetch(new Response(body, { status: 401, headers })),
      });
      const err = await client.fetchJson('GET', '/me').catch((e: unknown) => e);
      expect(err, body).toBeInstanceOf(UnauthorizedError);
      expect((err as Error).message, body).not.toContain('tok-secret');
    }
  });

  it('keeps an ordinary 401 an UnauthorizedError when reading its body fails', async () => {
    const res = new Response('ignored', { status: 401, headers: html });
    Object.defineProperty(res, 'text', { value: () => Promise.reject(new Error('stream broke')) });
    const client = createApiClient({ baseUrl: 'https://x.test', getToken: () => 't', fetchImpl: stubFetch(res) });
    await expect(client.fetchJson('GET', '/me')).rejects.toBeInstanceOf(UnauthorizedError);
  });
});

describe('detectEdgeBlock stays cheap on a hostile body', () => {
  it('scans a 200 KB adversarial body inside the 100 ms budget redos.test.ts uses', () => {
    // `<title` repeated with no `>` makes `<title[^>]*>` scan to the end from
    // every occurrence — quadratic over the whole body. Every non-2xx body a
    // client sees passes through here, so the scan is bounded instead.
    const hostile = '<title'.repeat(200_000 / 6);
    const started = performance.now();
    expect(detectEdgeBlock({ body: hostile })).toBeNull();
    expect(performance.now() - started).toBeLessThan(100);
  });

  it('still finds a marker inside the scanned prefix', () => {
    expect(detectEdgeBlock({ body: `${' '.repeat(2000)}Incapsula incident ID: 1${'x'.repeat(200_000)}` })).toEqual({
      vendor: 'Imperva',
    });
  });
});
