import { describe, expect, it, vi } from 'vitest';

import { CookieSessionManager, TokenManager, type BearerTokens, type StatePersistence } from './index.js';
import { EdgeBlockedError, UnauthorizedError, createApiClient } from '../http/index.js';

/**
 * A CDN/WAF refusal page must never trigger a refresh or a re-login
 * (chrischall/mcp-host#1015). Nothing judged the credential, so spending a
 * refresh on it — and on a rotating-token server, burning a rotation — or
 * throwing away a cookie session buys nothing: the replay meets the same edge.
 */

const CLOUDFRONT_401 = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>401 ERROR</H1>
<H2>The request could not be satisfied.</H2>
Request blocked.
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 7xXbE3cOQ2V0nY_example==
</PRE>
</BODY></HTML>`;

const IMPERVA_403 = `<html><head><META NAME="robots" CONTENT="noindex,nofollow"></head>
<body>Request unsuccessful. Incapsula incident ID: 1234000560012345678-90123456789</body></html>`;

const blocked401 = (): Response =>
  new Response(CLOUDFRONT_401, { status: 401, headers: { 'content-type': 'text/html' } });

function managerWithStore() {
  const refresh = vi.fn(async () => ({ accessToken: 'AT2', refreshToken: 'RT2', expiresAt: Date.now() + 3_600_000 }));
  const clear = vi.fn();
  const saved: BearerTokens[] = [];
  const store: StatePersistence<BearerTokens> = {
    load: () => ({ accessToken: 'AT', refreshToken: 'RT-rotated', expiresAt: Date.now() + 3_600_000 }),
    save: (t) => {
      saved.push(t);
    },
    clear,
  };
  const login = vi.fn(async () => ({ accessToken: 'AT-login', refreshToken: 'RT-login', expiresAt: Date.now() + 3_600_000 }));
  const tm = new TokenManager({ initial: login, refresh, persistence: store });
  return { tm, refresh, clear, saved, login };
}

describe('TokenManager.withAuth on a CDN/WAF block', () => {
  it('does not refresh or replay a 401 that is a refusal page, and returns it readable', async () => {
    const { tm, refresh, clear, saved, login } = managerWithStore();
    const call = vi.fn(async () => blocked401());
    const res = await tm.withAuth(call);
    expect(res.status).toBe(401);
    expect(call).toHaveBeenCalledTimes(1);
    expect(refresh).not.toHaveBeenCalled();
    expect(login).not.toHaveBeenCalled();
    expect(clear).not.toHaveBeenCalled();
    expect(saved).toEqual([]);
    // The caller still gets the body to judge.
    expect(await res.text()).toContain('The request could not be satisfied');
  });

  it('does not refresh on a 401 carrying cf-mitigated, whatever the body', async () => {
    const { tm, refresh } = managerWithStore();
    const call = vi.fn(
      async () =>
        new Response('{}', { status: 401, headers: { 'cf-mitigated': 'challenge', 'content-type': 'application/json' } }),
    );
    await tm.withAuth(call);
    expect(call).toHaveBeenCalledTimes(1);
    expect(refresh).not.toHaveBeenCalled();
  });

  it('rethrows an EdgeBlockedError from the request untouched, without refreshing', async () => {
    const { tm, refresh } = managerWithStore();
    const err = new EdgeBlockedError(401, 'Akamai', { service: 'Svc' });
    await expect(tm.withAuth(async () => Promise.reject(err))).rejects.toBe(err);
    expect(refresh).not.toHaveBeenCalled();
  });

  it('through createApiClient: a 401 block page is one request, zero refreshes, EdgeBlockedError', async () => {
    const { tm, refresh } = managerWithStore();
    const fetchImpl = vi.fn(async () => blocked401()) as unknown as typeof fetch;
    const client = createApiClient({ baseUrl: 'https://api.svc.test', tokenManager: tm, fetchImpl });
    const err = await client.fetchJson('GET', '/me').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect(fetchImpl).toHaveBeenCalledTimes(1);
    expect(refresh).not.toHaveBeenCalled();
  });

  it('control: a genuine 401 still refreshes once and replays once', async () => {
    const { tm, refresh } = managerWithStore();
    const seen: string[] = [];
    const call = vi.fn(async (token: string) => {
      seen.push(token);
      return seen.length === 1
        ? new Response('{"error":"invalid_token"}', { status: 401, headers: { 'content-type': 'application/json' } })
        : new Response('{}', { status: 200 });
    });
    const res = await tm.withAuth(call);
    expect(res.status).toBe(200);
    expect(seen).toEqual(['AT', 'AT2']);
    expect(refresh).toHaveBeenCalledOnce();
  });

  it('control: a genuine HTML 401 (an origin page) still refreshes once', async () => {
    const { tm, refresh } = managerWithStore();
    const call = vi
      .fn()
      .mockResolvedValueOnce(
        new Response('<html><title>401 Unauthorized</title></html>', { status: 401, headers: { 'content-type': 'text/html' } }),
      )
      .mockResolvedValueOnce(new Response('{}', { status: 200 }));
    expect((await tm.withAuth(call)).status).toBe(200);
    expect(refresh).toHaveBeenCalledOnce();
  });

  it('control: through createApiClient a genuine 401 refreshes once, then UnauthorizedError if it persists', async () => {
    const { tm, refresh } = managerWithStore();
    const fetchImpl = vi.fn(
      async () => new Response('{"error":"invalid_token"}', { status: 401, headers: { 'content-type': 'application/json' } }),
    ) as unknown as typeof fetch;
    const client = createApiClient({ baseUrl: 'https://api.svc.test', tokenManager: tm, fetchImpl });
    await expect(client.fetchJson('GET', '/me')).rejects.toBeInstanceOf(UnauthorizedError);
    expect(fetchImpl).toHaveBeenCalledTimes(2);
    expect(refresh).toHaveBeenCalledOnce();
  });
});

interface Sess {
  cookieHeader: string;
}

describe('CookieSessionManager.withSession on a CDN/WAF block', () => {
  function manager(isExpired: (res: Response) => boolean) {
    const login = vi.fn(async () => ({ cookieHeader: `s${login.mock.calls.length}` }));
    const mgr = new CookieSessionManager<Sess>({ login, isExpired });
    return { mgr, login };
  }
  // The common consumer heuristic: a 401/403, or HTML where JSON was expected.
  const statusExpired = (res: Response) => res.status === 401 || res.status === 403;

  it('does not re-login or replay when the "expired" response is a refusal page', async () => {
    const { mgr, login } = manager(statusExpired);
    const call = vi.fn(async () => new Response(IMPERVA_403, { status: 403, headers: { 'content-type': 'text/html' } }));
    const res = await mgr.withSession(call);
    expect(res.status).toBe(403);
    expect(call).toHaveBeenCalledTimes(1);
    expect(login).toHaveBeenCalledTimes(1); // the initial ensure(), no re-login
    expect(await res.text()).toContain('Incapsula');
  });

  it('does not re-login on a cf-mitigated challenge', async () => {
    const { mgr, login } = manager(statusExpired);
    const call = vi.fn(async () => new Response('', { status: 403, headers: { 'cf-mitigated': 'challenge' } }));
    await mgr.withSession(call);
    expect(call).toHaveBeenCalledTimes(1);
    expect(login).toHaveBeenCalledTimes(1);
  });

  it('judges a non-Response result carrying status + body (a fetchproxy HttpResponse)', async () => {
    const login = vi.fn(async () => ({ cookieHeader: 's' }));
    const mgr = new CookieSessionManager<Sess, { status: number; body: string; url: string }>({
      login,
      isExpired: (r) => r.status === 401,
    });
    const call = vi.fn(async () => ({ status: 401, body: CLOUDFRONT_401, url: 'https://x.test/a' }));
    await mgr.withSession(call);
    expect(call).toHaveBeenCalledTimes(1);
    expect(login).toHaveBeenCalledTimes(1);
  });

  it('control: a genuinely expired session still re-logs in and replays exactly once', async () => {
    const { mgr, login } = manager(statusExpired);
    const call = vi
      .fn()
      .mockResolvedValueOnce(new Response('<html><title>Sign in</title></html>', { status: 401, headers: { 'content-type': 'text/html' } }))
      .mockResolvedValueOnce(new Response('ok', { status: 200 }));
    const res = await mgr.withSession(call);
    expect(res.status).toBe(200);
    expect(call).toHaveBeenCalledTimes(2);
    expect(login).toHaveBeenCalledTimes(2);
  });

  it('control: a 200 is never inspected or replayed', async () => {
    const { mgr, login } = manager(() => false);
    const call = vi.fn(async () => new Response('fine', { status: 200 }));
    expect(await (await mgr.withSession(call)).text()).toBe('fine');
    expect(login).toHaveBeenCalledTimes(1);
  });
});
