import { describe, expect, it } from 'vitest';

import {
  FetchproxyHttpError,
  registerAdaptiveHealthcheckTool,
  runBridgeHealthcheck,
  type BridgeHealthcheckResult,
  type BridgeHealthcheckTransport,
  type BridgeProbeResult,
  type RegisterBridgeHealthcheckToolArgs,
} from './index.js';
import { EdgeBlockedError } from '../http/index.js';
import { createTestHarness, parseToolResult } from '../test/index.js';

/**
 * A CDN/WAF refusal page answering the bridge healthcheck's probe
 * (chrischall/mcp-host#1015). The bridge did its job — the request rode the
 * browser and came back with the edge's page — and the session behind it was
 * never evaluated, so neither "the bridge returned a protocol error" nor a
 * consumer's "session expired" is the true answer.
 */

const CLOUDFRONT_BLOCK = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
Request blocked.
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 7xXbE3cOQ2V0nY_example==
</PRE>
</BODY></HTML>`;

const CLOUDFLARE_CHALLENGE = `<!DOCTYPE html><html><head><title>Just a moment...</title></head>
<body><script>window._cf_chl_opt={cvId:'3'}</script></body></html>`;

function bridgeOf(kind: string | undefined, role: 'host' | null = 'host'): BridgeProbeResult['bridge'] {
  return {
    role,
    port: 37149,
    server_version: '3.3.0',
    fetch_timeout_ms: 30000,
    last_success_at: null,
    last_failure_at: kind ? Date.now() : null,
    last_failure_reason: kind ?? null,
    consecutive_failures: kind ? 1 : 0,
  } as BridgeProbeResult['bridge'];
}

/**
 * A transport whose runProbe calls the probe and classifies its throw the way
 * the real one does at the level these tests need: an HTTP error is `http`,
 * anything else is `other`.
 */
function fakeTransport(role: 'host' | null = 'host'): BridgeHealthcheckTransport {
  let lastKind: string | undefined;
  return {
    async runProbe(fetchFn, probePath) {
      try {
        await fetchFn(probePath);
        return { ok: true, elapsed_ms: 3, bridge: bridgeOf(undefined, role) };
      } catch (e) {
        lastKind = e instanceof FetchproxyHttpError ? 'http' : 'other';
        return {
          ok: false,
          elapsed_ms: 3,
          bridge: bridgeOf(lastKind, role),
          error: { kind: lastKind, message: e instanceof Error ? e.message : String(e) },
        } as BridgeProbeResult;
      }
    },
    status() {
      return { lastExtensionMessageAt: null, role, port: 37149 } as unknown as ReturnType<
        BridgeHealthcheckTransport['status']
      >;
    },
  };
}

async function run(
  thrown: unknown,
  extra: Partial<RegisterBridgeHealthcheckToolArgs> = {},
): Promise<BridgeHealthcheckResult> {
  const out = await runBridgeHealthcheck({
    server: {} as never,
    prefix: 'redfin',
    probePath: '/robots.txt',
    hostLabel: 'www.redfin.com',
    transport: fakeTransport(),
    probeFn: async () => {
      throw thrown;
    },
    ...extra,
  });
  return JSON.parse(out.content[0]!.text) as BridgeHealthcheckResult;
}

function httpError(status: number, body: string): FetchproxyHttpError {
  return new FetchproxyHttpError({ status, body, url: 'https://www.redfin.com/robots.txt' });
}

describe('bridge healthcheck on a CDN/WAF block', () => {
  it('reports edge_blocked for a CloudFront page carried on a FetchproxyHttpError', async () => {
    const r = await run(httpError(403, CLOUDFRONT_BLOCK));
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.detail).toEqual({ vendor: 'CloudFront' });
    expect(r.hint).toMatch(/CDN\/WAF \(CloudFront\)/);
    expect(r.hint).toMatch(/never evaluated/);
    expect(r.hint).not.toMatch(/protocol error/);
    // The bridge block is still reported: it worked.
    expect(r.bridge?.role).toBe('host');
  });

  it('reports edge_blocked for a Cloudflare challenge page', async () => {
    const r = await run(httpError(403, CLOUDFLARE_CHALLENGE));
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.detail).toEqual({ vendor: 'Cloudflare' });
  });

  it('reports edge_blocked from cf-mitigated on an error that carries headers', async () => {
    const err = Object.assign(new Error('HTTP 403'), { status: 403, headers: { 'cf-mitigated': 'challenge' } });
    const r = await run(err);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.detail).toEqual({ vendor: 'Cloudflare' });
  });

  it('reports edge_blocked for an EdgeBlockedError thrown by the consumer client', async () => {
    const r = await run(new EdgeBlockedError(403, 'Akamai', { service: 'Workday', method: 'GET', path: '/x' }));
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.detail).toEqual({ vendor: 'Akamai' });
  });

  it('says so on the direct leg too, and points at the bridge', async () => {
    const r = await run(httpError(403, CLOUDFRONT_BLOCK), {
      transport: () => undefined,
      path: () => ({ transport: 'direct', mode: 'auto' }),
    });
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.hint).toMatch(/CDN\/WAF/);
    expect(r.hint).toMatch(/ContextMint Bridge/);
  });

  it('lets a hints.edge_blocked override replace the copy', async () => {
    const r = await run(httpError(403, CLOUDFRONT_BLOCK), { hints: { edge_blocked: 'custom edge copy' } });
    expect(r.hint).toBe('custom edge copy');
  });

  it('still lets the consumer classifier decide first, keeping the vendor when it gives no detail', async () => {
    const r = await run(httpError(403, CLOUDFRONT_BLOCK), {
      classifyThrown: () => ({ kind: 'session_expired', hint: 'consumer copy' }),
    });
    expect(r.error?.kind).toBe('session_expired');
    expect(r.hint).toBe('consumer copy');
    expect(r.error?.detail).toEqual({ vendor: 'CloudFront' });
  });

  it('is inherited by registerAdaptiveHealthcheckTool on the bridge arm', async () => {
    const harness = await createTestHarness((server) =>
      registerAdaptiveHealthcheckTool({
        server,
        prefix: 'mah',
        hostLabel: 'my.atriumhealth.org',
        usingBridge: () => true,
        bridge: {
          probePath: 'Home',
          transport: fakeTransport(),
          probeFn: async () => {
            throw httpError(403, CLOUDFRONT_BLOCK);
          },
        },
        credential: { probePath: '/Home', resolveCredential: async () => ({ source: 'env' }), probeFn: async () => {} },
      }),
    );
    const r = parseToolResult<BridgeHealthcheckResult>(await harness.callTool('mah_healthcheck'));
    expect(r.error?.kind).toBe('edge_blocked');
    await harness.close();
  });
});

describe('bridge healthcheck outcomes that are not blocks are unchanged', () => {
  it('keeps an ordinary 403 an http error with the protocol copy', async () => {
    const r = await run(httpError(403, '<html><title>403 Forbidden</title></html>'));
    expect(r.error?.kind).toBe('http');
    expect(r.error?.detail).toBeUndefined();
    expect(r.hint).toMatch(/protocol error/);
  });

  it('keeps a CloudFront 502 page an http error: the origin is down, nothing was blocked', async () => {
    const r = await run(httpError(502, CLOUDFRONT_BLOCK.replace('403 ERROR', '502 ERROR')));
    expect(r.error?.kind).toBe('http');
  });

  it('keeps an unclassified throw unknown', async () => {
    const r = await run(new Error('something odd'));
    expect(r.error?.kind).toBe('unknown');
    expect(r.hint).toMatch(/Unexpected error/);
  });

  it('keeps an ok probe ok', async () => {
    const out = await runBridgeHealthcheck({
      server: {} as never,
      prefix: 'redfin',
      probePath: '/robots.txt',
      hostLabel: 'www.redfin.com',
      transport: fakeTransport(),
      probeFn: async () => 'User-agent: *',
    });
    const r = JSON.parse(out.content[0]!.text) as BridgeHealthcheckResult;
    expect(r.ok).toBe(true);
    expect(r.error).toBeUndefined();
  });
});
