/**
 * Binary-output kit — write tool-generated bytes (images, maps, exports) to a
 * configurable directory instead of dumping megabytes of base64 into a tool
 * result.
 *
 * Consolidates the duplicated trio in gemini (`images.ts#resolveOutputDir` /
 * `uniquePath` / `writeImage`) and flightaware (`shared.ts#resolveOutputDir` /
 * `writePng`): per-call dir → `<SVC>_OUTPUT_DIR` env → cwd, non-overwriting
 * filenames, extension derived from the MIME type. The fleet convention (see
 * the mcp-fleet-builder skill) is that every binary-output tool uses this shape.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { expandPath, readEnvVar, type EnvSource } from '../config/index.js';

/**
 * Resolve the directory a binary-output tool should write into:
 * the per-call argument → the named env var → the current working directory.
 * `~` and relative paths are expanded ({@link expandPath}) and the directory is
 * created recursively so the subsequent write can't ENOENT.
 */
export function resolveOutputDir(
  perCall: string | undefined,
  envVar: string,
  opts: { env?: EnvSource } = {},
): string {
  const raw = perCall ?? readEnvVar(envVar, opts.env ? { env: opts.env } : {});
  if (!raw) return process.cwd();
  const dir = expandPath(raw);
  mkdirSync(dir, { recursive: true });
  return dir;
}

/**
 * Reduce a caller-supplied filename stem to a single safe path component:
 * strip directory separators and any `..`, so the stem can never escape the
 * output directory (defense-in-depth — `SafePathSegment` does the same for
 * request-path atoms). A stem that sanitizes away entirely falls back to
 * `'file'`.
 */
function sanitizeBaseName(base: string): string {
  const safe = base
    .replace(/[/\\]+/g, '_') // kill path separators
    .replace(/\.\.+/g, '_') // neutralize .. (and longer dot runs)
    .replace(/^\.+/, '') // no leading dots (hidden-file / current-dir)
    .trim();
  return safe.length > 0 ? safe : 'file';
}

/**
 * A non-overwriting path for `base.ext` in `dir`: the bare name when free,
 * else `base-2.ext`, `base-3.ext`, … (gemini's numbering). `ext` is passed
 * without the dot. `base` is sanitized to a single path component
 * ({@link sanitizeBaseName}) so a `../…` stem can't write outside `dir`.
 */
export function uniquePath(dir: string, base: string, ext: string): string {
  const safe = sanitizeBaseName(base);
  const first = join(dir, `${safe}.${ext}`);
  if (!existsSync(first)) return first;
  for (let n = 2; ; n++) {
    const candidate = join(dir, `${safe}-${n}.${ext}`);
    if (!existsSync(candidate)) return candidate;
  }
}

/** Extensions for the MIME types the fleet's binary tools emit. */
const MIME_EXT: Record<string, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/webp': 'webp',
  'image/gif': 'gif',
  'application/pdf': 'pdf',
  'application/json': 'json',
};

/** Options for {@link writeBinaryOutput}. */
export interface WriteBinaryOutputOptions {
  /** Directory to write into (already resolved — see {@link resolveOutputDir}). */
  dir: string;
  /** Filename stem (no extension). */
  baseName: string;
  /** The bytes, base64-encoded (as returned by generation APIs). */
  base64: string;
  /** MIME type used to derive the extension when `extension` is not given. */
  mimeType?: string;
  /** Explicit extension (no dot); overrides the MIME lookup. */
  extension?: string;
}

/**
 * Decode `base64` and write it to a **non-overwriting** file in `dir`, deriving
 * the extension from `extension` → the MIME type → `'bin'`. Returns the
 * absolute path written. The caller returns that path from the tool result
 * (with an `inline` flag for base64 via `imageResult` when the user asks).
 */
export function writeBinaryOutput(opts: WriteBinaryOutputOptions): string {
  const ext = opts.extension ?? (opts.mimeType ? MIME_EXT[opts.mimeType] : undefined) ?? 'bin';
  mkdirSync(opts.dir, { recursive: true });
  const path = uniquePath(opts.dir, opts.baseName, ext);
  writeFileSync(path, Buffer.from(opts.base64, 'base64'));
  return path;
}

/**
 * Magic-byte MIME sniff for the image formats the fleet passes around
 * (PNG / JPEG / WebP / GIF). Returns `undefined` for anything else — callers
 * decide their own default. Pairs with `readFileHead` for on-disk files;
 * consolidates gemini's `sniffMimeBytes` (and evite's dimension sniffer uses
 * the same signatures).
 */
export function sniffMimeBytes(bytes: Uint8Array): string | undefined {
  const buf = Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  if (buf.length >= 8 && buf.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) {
    return 'image/png';
  }
  if (buf.length >= 3 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) {
    return 'image/jpeg';
  }
  if (buf.length >= 12 && buf.subarray(0, 4).toString('latin1') === 'RIFF' && buf.subarray(8, 12).toString('latin1') === 'WEBP') {
    return 'image/webp';
  }
  if (buf.length >= 4 && buf.subarray(0, 4).toString('latin1') === 'GIF8') {
    return 'image/gif';
  }
  return undefined;
}
