/**
 * Binary-output kit — write tool-generated bytes (images, maps, exports) to a
 * configurable directory instead of dumping megabytes of base64 into a tool
 * result.
 *
 * Consolidates the duplicated trio in gemini (`images.ts#resolveOutputDir` /
 * `uniquePath` / `writeImage`) and flightaware (`shared.ts#resolveOutputDir` /
 * `writePng`): per-call dir → `<SVC>_OUTPUT_DIR` env → cwd, non-overwriting
 * filenames, extension derived from the MIME type. The fleet convention (see
 * the mcp-fleet-builder skill) is that every binary-output tool uses this shape.
 */

import { existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

import { expandPath, readEnvVar, type EnvSource } from '../config/index.js';
import { assertPathWithinRoots } from './confine.js';
import { sanitizeBaseName, writeUniqueFileSync } from './write.js';

/**
 * Resolve the directory a binary-output tool should write into:
 * the per-call argument → the named env var → the current working directory.
 * `~` and relative paths are expanded ({@link expandPath}) and the directory is
 * created recursively so the subsequent write can't ENOENT.
 *
 * `allowedRoots` (opt-in) confines the **per-call** directory — the value a
 * tool argument supplies — to those roots, checked through symlinks before
 * anything is created. The env var and cwd are operator configuration and are
 * not constrained.
 */
export function resolveOutputDir(
  perCall: string | undefined,
  envVar: string,
  opts: { env?: EnvSource; allowedRoots?: readonly string[] } = {},
): string {
  const raw = perCall ?? readEnvVar(envVar, opts.env ? { env: opts.env } : {});
  if (!raw) return process.cwd();
  const dir = expandPath(raw);
  if (perCall !== undefined && opts.allowedRoots) {
    assertPathWithinRoots(dir, opts.allowedRoots);
    mkdirSync(dir, { recursive: true });
    // Re-check now it exists, in case a component was swapped for a symlink.
    assertPathWithinRoots(dir, opts.allowedRoots);
    return dir;
  }
  mkdirSync(dir, { recursive: true });
  return dir;
}

/**
 * A non-overwriting path for `base.ext` in `dir`: the bare name when free,
 * else `base-2.ext`, `base-3.ext`, … (gemini's numbering). `ext` is passed
 * without the dot. `base` is sanitized to a single path component so a `../…`
 * stem can't write outside `dir`.
 *
 * Check-then-use: the name can be taken (or a symlink planted there) between
 * this call and the caller's write. To write, prefer {@link writeUniqueFile} /
 * {@link writeBinaryOutput}, which claim the name with an exclusive create.
 */
export function uniquePath(dir: string, base: string, ext: string): string {
  const safe = sanitizeBaseName(base);
  const first = join(dir, `${safe}.${ext}`);
  if (!existsSync(first)) return first;
  for (let n = 2; ; n++) {
    const candidate = join(dir, `${safe}-${n}.${ext}`);
    if (!existsSync(candidate)) return candidate;
  }
}

/** Extensions for the MIME types the fleet's binary tools emit. */
const MIME_EXT: Record<string, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/webp': 'webp',
  'image/gif': 'gif',
  'image/heic': 'heic',
  'image/avif': 'avif',
  'application/pdf': 'pdf',
  'application/json': 'json',
  'application/zip': 'zip',
  'audio/midi': 'mid',
  'video/mp4': 'mp4',
  'video/quicktime': 'mov',
};

/** Options for {@link writeBinaryOutput}. */
export interface WriteBinaryOutputOptions {
  /** Directory to write into (already resolved — see {@link resolveOutputDir}). */
  dir: string;
  /** Filename stem (no extension). */
  baseName: string;
  /** The bytes, base64-encoded (as returned by generation APIs). */
  base64: string;
  /** MIME type used to derive the extension when `extension` is not given. */
  mimeType?: string;
  /** Explicit extension (no dot); overrides the MIME lookup. */
  extension?: string;
  /** File mode for the new file (before umask), e.g. `0o600`. Default `0o666`. */
  mode?: number;
}

/**
 * Decode `base64` and write it to a **non-overwriting** file in `dir`, deriving
 * the extension from `extension` → the MIME type → `'bin'`. Returns the
 * absolute path written. The caller returns that path from the tool result
 * (with an `inline` flag for base64 via `imageResult` when the user asks).
 *
 * Each candidate name is claimed with an exclusive, no-follow create
 * (`O_CREAT | O_EXCL | O_NOFOLLOW`) and the next name tried on EEXIST, so the
 * write is race-free and never goes through a symlink planted at the name —
 * previously a dangling symlink there looked "free" to `existsSync` and the
 * write created its target outside `dir`.
 */
export function writeBinaryOutput(opts: WriteBinaryOutputOptions): string {
  const ext = opts.extension ?? (opts.mimeType ? MIME_EXT[opts.mimeType] : undefined) ?? 'bin';
  return writeUniqueFileSync(opts.dir, opts.baseName, ext, Buffer.from(opts.base64, 'base64'), opts.mode);
}
