import { describe, expect, it, vi } from 'vitest';

import { createOAuth2Refresher, OAuth2RefreshError } from './index.js';
import { EdgeBlockedError } from '../http/index.js';
import { TokenManager, type BearerTokens, type StatePersistence } from '../session/index.js';

/**
 * A CDN/WAF in front of a token endpoint refusing the refresh grant is not the
 * endpoint rejecting the refresh token (chrischall/mcp-host#1015).
 *
 * The cost of confusing the two is a lost credential: TokenManager's default
 * `isRefreshRevoked` reads a 4xx OAuth2RefreshError as "revoked" and CLEARS the
 * stored tokens — and with a rotating refresh token, the stored one is the only
 * live copy. canvas-parent, musicbrainz and skylight all refresh through
 * `createOAuth2Refresher`.
 */

/** The CloudFront page Zola's API answered with on 2026-10-01, as served. */
const CLOUDFRONT_BLOCK = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 7xXbE3cOQ2V0nY_example==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>`;

const CLOUDFLARE_CHALLENGE = `<!DOCTYPE html><html><head><title>Just a moment...</title></head>
<body><script>window._cf_chl_opt={cvId:'3'}</script></body></html>`;

function cloudFront403(): Response {
  return new Response(CLOUDFRONT_BLOCK, {
    status: 403,
    statusText: 'Forbidden',
    headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront', server: 'CloudFront' },
  });
}

function cloudflareChallenge(status: number): Response {
  return new Response(CLOUDFLARE_CHALLENGE, {
    status,
    headers: { 'content-type': 'text/html', 'cf-mitigated': 'challenge' },
  });
}

function json(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
}

function counting(make: () => Response) {
  const calls = { n: 0 };
  const fetchImpl = vi.fn(async () => {
    calls.n += 1;
    return make();
  }) as unknown as typeof fetch;
  return { fetchImpl, calls };
}

describe('createOAuth2Refresher on a CDN/WAF block', () => {
  it('pins the premise: the page markers sit past the 200 characters the error message keeps', () => {
    // Why the full body has to be scanned BEFORE truncation.
    expect(CLOUDFRONT_BLOCK.indexOf('ERROR: The request could not be satisfied')).toBeGreaterThan(190);
    expect(CLOUDFRONT_BLOCK.indexOf('Generated by cloudfront')).toBeGreaterThan(200);
  });

  it('throws EdgeBlockedError, not OAuth2RefreshError, for the CloudFront 403 page', async () => {
    const { fetchImpl } = counting(cloudFront403);
    const refresh = createOAuth2Refresher({
      endpoint: 'https://auth.svc.test/oauth/token',
      refreshToken: 'rt-secret',
      fetchImpl,
    });
    const err = await refresh().catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect(err).not.toBeInstanceOf(OAuth2RefreshError);
    expect((err as EdgeBlockedError).status).toBe(403);
    expect((err as EdgeBlockedError).vendor).toBe('CloudFront');
    const message = (err as Error).message;
    expect(message).toContain('auth.svc.test');
    expect(message).toContain('POST /oauth/token');
    expect(message).toMatch(/credential was not evaluated/);
    // Neither the page nor the grant reaches the message.
    expect(message).not.toContain('<HTML>');
    expect(message).not.toContain('rt-secret');
  });

  it('throws EdgeBlockedError for a Cloudflare challenge, from cf-mitigated or the page, at 403 or 503', async () => {
    for (const status of [403, 503]) {
      const { fetchImpl } = counting(() => cloudflareChallenge(status));
      const refresh = createOAuth2Refresher({ endpoint: 'https://auth.svc.test/token', refreshToken: 'rt', fetchImpl });
      const err = await refresh().catch((e: unknown) => e);
      expect(err, String(status)).toBeInstanceOf(EdgeBlockedError);
      expect((err as EdgeBlockedError).vendor, String(status)).toBe('Cloudflare');
      expect((err as EdgeBlockedError).status, String(status)).toBe(status);
    }
    // The header alone is enough, whatever the body says.
    const { fetchImpl } = counting(
      () => new Response('', { status: 403, headers: { 'cf-mitigated': 'challenge' } }),
    );
    const refresh = createOAuth2Refresher({ endpoint: 'https://auth.svc.test/token', refreshToken: 'rt', fetchImpl });
    await expect(refresh()).rejects.toBeInstanceOf(EdgeBlockedError);
  });

  it('does not retry a block: the same host meets the same edge', async () => {
    const { fetchImpl, calls } = counting(() => cloudflareChallenge(503));
    const refresh = createOAuth2Refresher({
      endpoint: 'https://auth.svc.test/token',
      refreshToken: 'rt',
      retry: { count: 3, delayMs: 0 },
      fetchImpl,
    });
    await expect(refresh()).rejects.toBeInstanceOf(EdgeBlockedError);
    expect(calls.n).toBe(1);
  });

  it('keeps a genuine invalid_grant (400 or 401) an OAuth2RefreshError carrying its status', async () => {
    for (const status of [400, 401]) {
      const { fetchImpl } = counting(() => json({ error: 'invalid_grant' }, status));
      const refresh = createOAuth2Refresher({ endpoint: 'https://auth.svc.test/token', refreshToken: 'rt', fetchImpl });
      const err = await refresh().catch((e: unknown) => e);
      expect(err, String(status)).toBeInstanceOf(OAuth2RefreshError);
      expect(err, String(status)).not.toBeInstanceOf(EdgeBlockedError);
      expect((err as OAuth2RefreshError).status).toBe(status);
      expect((err as Error).message).toContain('invalid_grant');
    }
  });

  it('keeps a CloudFront 502 an OAuth2RefreshError (the origin is down, nothing was blocked) and retries it', async () => {
    const { fetchImpl, calls } = counting(
      () => new Response(CLOUDFRONT_BLOCK.replace('403 ERROR', '502 ERROR'), { status: 502 }),
    );
    const refresh = createOAuth2Refresher({
      endpoint: 'https://auth.svc.test/token',
      refreshToken: 'rt',
      retry: { count: 1, delayMs: 0 },
      fetchImpl,
    });
    const err = await refresh().catch((e: unknown) => e);
    expect(err).toBeInstanceOf(OAuth2RefreshError);
    expect(calls.n).toBe(2);
  });
});

describe('TokenManager over createOAuth2Refresher, end to end', () => {
  function setup(make: () => Response) {
    const now = Date.now();
    const counters = { logins: 0, clears: 0 };
    const store: StatePersistence<BearerTokens> & { value: BearerTokens | null } = {
      // Expired, so the first call has to refresh. The refresh token was
      // rotated on an earlier run: this record is its only copy.
      value: { accessToken: 'at-old', refreshToken: 'rt-rotated', expiresAt: now - 1000 },
      load: () => store.value,
      save: (t) => {
        store.value = t;
      },
      clear: () => {
        counters.clears += 1;
        store.value = null;
      },
    };
    const refresher = createOAuth2Refresher({
      endpoint: 'https://auth.svc.test/token',
      refreshToken: 'rt-boot',
      fetchImpl: (async () => make()) as unknown as typeof fetch,
    });
    const mgr = new TokenManager({
      initial: async () => {
        counters.logins += 1;
        return { accessToken: 'at-login', refreshToken: 'rt-login', expiresAt: Date.now() + 3_600_000 };
      },
      refresh: async (rt) => {
        const r = await refresher(rt);
        return { accessToken: r.accessToken, expiresAt: Date.now() + 3_600_000 };
      },
      persistence: store,
    });
    return { mgr, store, counters };
  }

  it('keeps the stored refresh token when the refresh is blocked at the edge', async () => {
    const { mgr, store, counters } = setup(cloudFront403);
    await expect(mgr.getAccessToken()).rejects.toBeInstanceOf(EdgeBlockedError);
    expect(counters.clears).toBe(0);
    expect(counters.logins).toBe(0);
    expect(store.value?.refreshToken).toBe('rt-rotated');
  });

  it('keeps it through a Cloudflare challenge too', async () => {
    const { mgr, store, counters } = setup(() => cloudflareChallenge(403));
    await expect(mgr.getAccessToken()).rejects.toBeInstanceOf(EdgeBlockedError);
    expect(counters.clears).toBe(0);
    expect(store.value?.refreshToken).toBe('rt-rotated');
  });

  it('still clears it and re-logs in on a genuine invalid_grant', async () => {
    const { mgr, store, counters } = setup(() => json({ error: 'invalid_grant' }, 400));
    expect(await mgr.getAccessToken()).toBe('at-login');
    expect(counters.clears).toBe(1);
    expect(counters.logins).toBe(1);
    expect(store.value?.refreshToken).toBe('rt-login');
  });
});
